update severe_weather_open_fema_data_merge.disaster_summaries_merge_without_hazard_type_2 ofd
set disaster_title = disaster_name
from open_fema_data.fema_web_disaster_declarations_v1 dd
where ofd.disaster_number = dd.disaster_number::text