const tables = {
    nri: {
        name: 'nri_counties_november_2021',
        schema: 'national_risk_index',
        orig_columns: [
            // 'OID_',
            'NRI_ID','STCOFIPS',

            'POPULATION','BUILDVALUE','AGRIVALUE','RISK_SCORE',

            'RISK_RATNG',

            'EAL_VALT','EAL_VALB', 'EAL_VALA',

            'AVLN_EVNTS','AVLN_AFREQ','AVLN_EXPB','AVLN_EXPP','AVLN_EXPPE','AVLN_EXPT','AVLN_HLRB','AVLN_HLRP','AVLN_HLRR','AVLN_EALB','AVLN_EALP','AVLN_EALPE',
            'AVLN_EALT',
            'AVLN_EALS','AVLN_EALR','AVLN_RISKS','AVLN_RISKR','CFLD_EVNTS','CFLD_AFREQ','CFLD_EXPB','CFLD_EXPP','CFLD_EXPPE','CFLD_EXPT','CFLD_HLRB','CFLD_HLRP','CFLD_HLRR','CFLD_EALB','CFLD_EALP','CFLD_EALPE',
            'CFLD_EALT',
            'CFLD_EALS','CFLD_EALR','CFLD_RISKS','CFLD_RISKR','CWAV_EVNTS','CWAV_AFREQ','CWAV_EXPB','CWAV_EXPP','CWAV_EXPPE','CWAV_EXPA','CWAV_EXPT','CWAV_HLRB','CWAV_HLRP','CWAV_HLRA','CWAV_HLRR','CWAV_EALB','CWAV_EALP','CWAV_EALPE','CWAV_EALA',
            'CWAV_EALT',
            'CWAV_EALS','CWAV_EALR','CWAV_RISKS','CWAV_RISKR','DRGT_EVNTS','DRGT_AFREQ','DRGT_EXPA','DRGT_EXPT','DRGT_HLRA','DRGT_HLRR','DRGT_EALA',
            'DRGT_EALT',
            'DRGT_EALS', 'DRGT_EALR','DRGT_RISKS','DRGT_RISKR','ERQK_EVNTS','ERQK_AFREQ','ERQK_EXPB','ERQK_EXPP','ERQK_EXPPE','ERQK_EXPT','ERQK_HLRB','ERQK_HLRP','ERQK_HLRR','ERQK_EALB','ERQK_EALP','ERQK_EALPE',
            'ERQK_EALT',
            'ERQK_EALS','ERQK_EALR','ERQK_RISKS','ERQK_RISKR','HAIL_EVNTS','HAIL_AFREQ','HAIL_EXPB','HAIL_EXPP','HAIL_EXPPE','HAIL_EXPA','HAIL_EXPT','HAIL_HLRB','HAIL_HLRP','HAIL_HLRA','HAIL_HLRR','HAIL_EALB','HAIL_EALP','HAIL_EALPE','HAIL_EALA',
            'HAIL_EALT',
            'HAIL_EALS','HAIL_EALR','HAIL_RISKS','HAIL_RISKR','HWAV_EVNTS','HWAV_AFREQ','HWAV_EXPB','HWAV_EXPP','HWAV_EXPPE','HWAV_EXPA','HWAV_EXPT','HWAV_HLRB','HWAV_HLRP','HWAV_HLRA','HWAV_HLRR','HWAV_EALB','HWAV_EALP','HWAV_EALPE', 'HWAV_EALA',
            'HWAV_EALT',
            'HWAV_EALS','HWAV_EALR','HWAV_RISKS','HWAV_RISKR','HRCN_EVNTS','HRCN_AFREQ','HRCN_EXPB','HRCN_EXPP','HRCN_EXPPE','HRCN_EXPA','HRCN_EXPT','HRCN_HLRB','HRCN_HLRP','HRCN_HLRA','HRCN_HLRR','HRCN_EALB', 'HRCN_EALP','HRCN_EALPE','HRCN_EALA',
            'HRCN_EALT',
            'HRCN_EALS','HRCN_EALR','HRCN_RISKS','HRCN_RISKR','ISTM_EVNTS','ISTM_AFREQ','ISTM_EXPB','ISTM_EXPP','ISTM_EXPPE','ISTM_EXPT','ISTM_HLRB','ISTM_HLRP','ISTM_HLRR','ISTM_EALB','ISTM_EALP','ISTM_EALPE',
            'ISTM_EALT',
            'ISTM_EALS','ISTM_EALR','ISTM_RISKS','ISTM_RISKR','LNDS_EVNTS','LNDS_AFREQ','LNDS_EXPB','LNDS_EXPP','LNDS_EXPPE','LNDS_EXPT','LNDS_HLRB','LNDS_HLRP','LNDS_HLRR','LNDS_EALB','LNDS_EALP', 'LNDS_EALPE',
            'LNDS_EALT',
            'LNDS_EALS','LNDS_EALR','LNDS_RISKS','LNDS_RISKR','LTNG_EVNTS','LTNG_AFREQ','LTNG_EXPB','LTNG_EXPP','LTNG_EXPPE','LTNG_EXPT','LTNG_HLRB','LTNG_HLRP','LTNG_HLRR','LTNG_EALB','LTNG_EALP','LTNG_EALPE',
            'LTNG_EALT',
            'LTNG_EALS','LTNG_EALR','LTNG_RISKS','LTNG_RISKR','RFLD_EVNTS','RFLD_AFREQ','RFLD_EXPB','RFLD_EXPP','RFLD_EXPPE','RFLD_EXPA','RFLD_EXPT','RFLD_HLRB','RFLD_HLRP','RFLD_HLRA','RFLD_HLRR','RFLD_EALB','RFLD_EALP', 'RFLD_EALPE','RFLD_EALA',
            'RFLD_EALT',
            'RFLD_EALS','RFLD_EALR','RFLD_RISKS','RFLD_RISKR','SWND_EVNTS','SWND_AFREQ', 'SWND_EXPB','SWND_EXPP','SWND_EXPPE','SWND_EXPA','SWND_EXPT','SWND_HLRB','SWND_HLRP','SWND_HLRA','SWND_HLRR', 'SWND_EALB','SWND_EALP','SWND_EALPE','SWND_EALA',
            'SWND_EALT',
            'SWND_EALS','SWND_EALR','SWND_RISKS','SWND_RISKR', 'TRND_EVNTS','TRND_AFREQ','TRND_EXPB','TRND_EXPP','TRND_EXPPE','TRND_EXPA','TRND_EXPT','TRND_HLRB','TRND_HLRP', 'TRND_HLRA','TRND_HLRR','TRND_EALB','TRND_EALP','TRND_EALPE','TRND_EALA',
            'TRND_EALT',
            'TRND_EALS','TRND_EALR', 'TRND_RISKS','TRND_RISKR','TSUN_EVNTS','TSUN_AFREQ','TSUN_EXPB','TSUN_EXPP','TSUN_EXPPE','TSUN_EXPT','TSUN_HLRB', 'TSUN_HLRP','TSUN_HLRR','TSUN_EALB','TSUN_EALP','TSUN_EALPE',
            'TSUN_EALT',
            'TSUN_EALS','TSUN_EALR','TSUN_RISKS', 'TSUN_RISKR','VLCN_EVNTS','VLCN_AFREQ','VLCN_EXPB','VLCN_EXPP','VLCN_EXPPE','VLCN_EXPT','VLCN_HLRB','VLCN_HLRP', 'VLCN_HLRR','VLCN_EALB','VLCN_EALP','VLCN_EALPE',
            'VLCN_EALT',
            'VLCN_EALS','VLCN_EALR','VLCN_RISKS','VLCN_RISKR', 'WFIR_EVNTS','WFIR_AFREQ','WFIR_EXPB','WFIR_EXPP','WFIR_EXPPE','WFIR_EXPA','WFIR_EXPT','WFIR_HLRB','WFIR_HLRP', 'WFIR_HLRA','WFIR_HLRR','WFIR_EALB','WFIR_EALP','WFIR_EALPE','WFIR_EALA',
            'WFIR_EALT',
            'WFIR_EALS','WFIR_EALR', 'WFIR_RISKS','WFIR_RISKR','WNTW_EVNTS','WNTW_AFREQ','WNTW_EXPB','WNTW_EXPP','WNTW_EXPPE','WNTW_EXPA','WNTW_EXPT', 'WNTW_HLRB','WNTW_HLRP','WNTW_HLRA','WNTW_HLRR','WNTW_EALB','WNTW_EALP','WNTW_EALPE','WNTW_EALA',
            'WNTW_EALT',
            'WNTW_EALS','WNTW_EALR','WNTW_RISKS','WNTW_RISKR' //,'NRI_VER'
        ],
        numericColumns: [
            'POPULATION'
        ],
        floatColumns: [
            'BUILDVALUE','AGRIVALUE','RISK_SCORE','EAL_VALT','EAL_VALB', 'EAL_VALA',
            'AVLN_EALT','CFLD_EALT','CWAV_EALT','DRGT_EALT','ERQK_EALT','HAIL_EALT','HWAV_EALT',
            'HRCN_EALT','ISTM_EALT','LNDS_EALT','LTNG_EALT','RFLD_EALT','SWND_EALT','TRND_EALT','TSUN_EALT','VLCN_EALT','WFIR_EALT','WNTW_EALT',
            'AVLN_EVNTS','AVLN_AFREQ','AVLN_EXPB','AVLN_EXPP','AVLN_EXPPE','AVLN_EXPT','AVLN_HLRB','AVLN_HLRP','AVLN_EALB','AVLN_EALP','AVLN_EALPE',
            'AVLN_EALS','AVLN_RISKS', 'CFLD_EVNTS','CFLD_AFREQ','CFLD_EXPB','CFLD_EXPP','CFLD_EXPPE','CFLD_EXPT','CFLD_HLRB','CFLD_HLRP','CFLD_EALB','CFLD_EALP','CFLD_EALPE',
            'CFLD_EALS','CFLD_RISKS', 'CWAV_EVNTS','CWAV_AFREQ','CWAV_EXPB','CWAV_EXPP','CWAV_EXPPE','CWAV_EXPA','CWAV_EXPT','CWAV_HLRB','CWAV_HLRP','CWAV_HLRA','CWAV_EALB','CWAV_EALP','CWAV_EALPE','CWAV_EALA',
            'CWAV_EALS','CWAV_RISKS','DRGT_EVNTS','DRGT_AFREQ','DRGT_EXPA','DRGT_EXPT','DRGT_HLRA','DRGT_EALA',
            'DRGT_EALS','DRGT_RISKS','ERQK_EVNTS','ERQK_AFREQ','ERQK_EXPB','ERQK_EXPP','ERQK_EXPPE','ERQK_EXPT','ERQK_HLRB','ERQK_HLRP','ERQK_EALB','ERQK_EALP','ERQK_EALPE',
            'ERQK_EALS','ERQK_RISKS','HAIL_EVNTS','HAIL_AFREQ','HAIL_EXPB','HAIL_EXPP','HAIL_EXPPE','HAIL_EXPA','HAIL_EXPT','HAIL_HLRB','HAIL_HLRP','HAIL_HLRA','HAIL_EALB','HAIL_EALP','HAIL_EALPE','HAIL_EALA',
            'HAIL_EALS','HAIL_RISKS','HWAV_EVNTS','HWAV_AFREQ','HWAV_EXPB','HWAV_EXPP','HWAV_EXPPE','HWAV_EXPA','HWAV_EXPT','HWAV_HLRB','HWAV_HLRP','HWAV_HLRA','HWAV_EALB','HWAV_EALP','HWAV_EALPE', 'HWAV_EALA',
            'HWAV_EALS','HWAV_RISKS','HRCN_EVNTS','HRCN_AFREQ','HRCN_EXPB','HRCN_EXPP','HRCN_EXPPE','HRCN_EXPA','HRCN_EXPT','HRCN_HLRB','HRCN_HLRP','HRCN_HLRA','HRCN_EALB', 'HRCN_EALP','HRCN_EALPE','HRCN_EALA',
            'HRCN_EALS','HRCN_RISKS','ISTM_EVNTS','ISTM_AFREQ','ISTM_EXPB','ISTM_EXPP','ISTM_EXPPE','ISTM_EXPT','ISTM_HLRB','ISTM_HLRP','ISTM_EALB','ISTM_EALP','ISTM_EALPE',
            'ISTM_EALS','ISTM_RISKS','LNDS_EVNTS','LNDS_AFREQ','LNDS_EXPB','LNDS_EXPP','LNDS_EXPPE','LNDS_EXPT','LNDS_HLRB','LNDS_HLRP','LNDS_EALB','LNDS_EALP', 'LNDS_EALPE',
            'LNDS_EALS','LNDS_RISKS','LTNG_EVNTS','LTNG_AFREQ','LTNG_EXPB','LTNG_EXPP','LTNG_EXPPE','LTNG_EXPT','LTNG_HLRB','LTNG_HLRP','LTNG_EALB','LTNG_EALP','LTNG_EALPE',
            'LTNG_EALS','LTNG_RISKS','RFLD_EVNTS','RFLD_AFREQ','RFLD_EXPB','RFLD_EXPP','RFLD_EXPPE','RFLD_EXPA','RFLD_EXPT','RFLD_HLRB','RFLD_HLRP','RFLD_HLRA','RFLD_EALB','RFLD_EALP', 'RFLD_EALPE','RFLD_EALA',
            'RFLD_EALS','RFLD_RISKS','SWND_EVNTS','SWND_AFREQ', 'SWND_EXPB','SWND_EXPP','SWND_EXPPE','SWND_EXPA','SWND_EXPT','SWND_HLRB','SWND_HLRP','SWND_HLRA', 'SWND_EALB','SWND_EALP','SWND_EALPE','SWND_EALA',
            'SWND_EALS','SWND_RISKS', 'TRND_EVNTS','TRND_AFREQ','TRND_EXPB','TRND_EXPP','TRND_EXPPE','TRND_EXPA','TRND_EXPT','TRND_HLRB','TRND_HLRP', 'TRND_HLRA','TRND_EALB','TRND_EALP','TRND_EALPE','TRND_EALA',
            'TRND_EALS','TRND_RISKS','TSUN_EVNTS','TSUN_AFREQ','TSUN_EXPB','TSUN_EXPP','TSUN_EXPPE','TSUN_EXPT','TSUN_HLRB', 'TSUN_HLRP','TSUN_EALB','TSUN_EALP','TSUN_EALPE',
            'TSUN_EALS','TSUN_RISKS','VLCN_EVNTS','VLCN_AFREQ','VLCN_EXPB','VLCN_EXPP','VLCN_EXPPE','VLCN_EXPT','VLCN_HLRB','VLCN_HLRP','VLCN_EALB','VLCN_EALP','VLCN_EALPE',
            'VLCN_EALS','VLCN_RISKS', 'WFIR_EVNTS','WFIR_AFREQ','WFIR_EXPB','WFIR_EXPP','WFIR_EXPPE','WFIR_EXPA','WFIR_EXPT','WFIR_HLRB','WFIR_HLRP', 'WFIR_HLRA','WFIR_EALB','WFIR_EALP','WFIR_EALPE','WFIR_EALA',
            'WFIR_EALS', 'WFIR_RISKS','WNTW_EVNTS','WNTW_AFREQ','WNTW_EXPB','WNTW_EXPP','WNTW_EXPPE','WNTW_EXPA','WNTW_EXPT', 'WNTW_HLRB','WNTW_HLRP','WNTW_HLRA','WNTW_EALB','WNTW_EALP','WNTW_EALPE','WNTW_EALA',
            'WNTW_EALS','WNTW_RISKS'
        ],
        dateColumns: [

        ],
        booleanColumns: [

        ]
    }
}

tables.nri.columns = tables.nri.orig_columns.map(col => ({
    name: col.toLowerCase(),
    dataType: tables.nri.numericColumns.includes(col) ? 'double precision' :
        tables.nri.floatColumns.includes(col) ? 'double precision' :
            tables.nri.dateColumns.includes(col) ? 'timestamp with time zone' :
                tables.nri.booleanColumns.includes(col) ? 'boolean' : 'character varying'
}))

module.exports = {
    tables
}